from shared_foundation.models.abstract_bigpk import AbstractSharedBigPk
from shared_foundation.models.abstract_thing import AbstractSharedThing
from shared_foundation.models.profile import SharedProfile
from shared_foundation.models.university import SharedUniversity
from shared_foundation.models.university import SharedUniveristyDomain
from shared_foundation.models.universityregistration import SharedUniversityRegistration
