# -*- coding: utf-8 -*-
from django.utils.translation import ugettext_lazy as _
from django.conf import settings


# The domain of our application.
#

ACADEMICSTODAY_APP_HTTP_PROTOCOL = settings.ACADEMICSTODAY_APP_HTTP_PROTOCOL
ACADEMICSTODAY_APP_HTTP_DOMAIN = settings.ACADEMICSTODAY_APP_HTTP_DOMAIN


# The constants to be used for the university acceptance criteria.
#

NO_REGISTRATION_REQUIREMENT_ID = 1
OPEN_REGISTRATION_REQUIREMENT_ID = 2
RESTRICTIVE_REGISTRATION_REQUIREMENT_ID = 3
CLOSED_REGISTRATION_REQUIREMENT_ID = 4

NO_REGISTRATION_REQUIREMENT_TEXT = _('No registration required')
OPEN_REGISTRATION_REQUIREMENT_TEXT = _('Requires registration with automatic acceptance')
RESTRICTIVE_REGISTRATION_REQUIREMENT_TEXT = _('Requires registration with manual acceptance by administrator')
CLOSED_REGISTRATION_REQUIREMENT_TEXT = _('Registration is closed')

REGISTRATION_REQUIREMENT_OPTIONS = (
    (NO_REGISTRATION_REQUIREMENT_ID, NO_REGISTRATION_REQUIREMENT_TEXT),
    (OPEN_REGISTRATION_REQUIREMENT_ID, OPEN_REGISTRATION_REQUIREMENT_TEXT),
    (RESTRICTIVE_REGISTRATION_REQUIREMENT_ID, RESTRICTIVE_REGISTRATION_REQUIREMENT_TEXT),
    (CLOSED_REGISTRATION_REQUIREMENT_ID, CLOSED_REGISTRATION_REQUIREMENT_TEXT),
)
