# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_foundation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareduniversityregistration',
            name='owner',
        ),
        migrations.AddField(
            model_name='shareduniversity',
            name='is_content_open',
            field=models.BooleanField(default=True, help_text='Variable controls whether non-registered users are able to view the contents of the university or users must be registered to view. This includes: courses, forums, etc.', verbose_name='Is Content Open'),
        ),
        migrations.AddField(
            model_name='shareduniversity',
            name='is_listed',
            field=models.BooleanField(default=True, help_text='Variable controls whether this university will be listed to the public.', verbose_name='Is Listed'),
        ),
        migrations.AddField(
            model_name='shareduniversity',
            name='registration_requirement',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'No registration required'), (2, 'Requires registration with automatic acceptance'), (3, 'Requires registration with manual acceptance by administrator'), (4, 'Registration is closed')], default=1, help_text='The registration requirement for students to be accepted into this university.', verbose_name='Registration Reqirement'),
        ),
        migrations.DeleteModel(
            name='SharedUniversityRegistration',
        ),
    ]
