# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 00:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared_foundation', '0002_auto_20170919_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareduniversity',
            name='applicants',
            field=models.ManyToManyField(blank=True, help_text='The users who have applied to this university and require admission decision by an administrator.', related_name='shared_foundation_shareduniversity_applicants_related', to=settings.AUTH_USER_MODEL),
        ),
    ]
