# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0029_auto_20150227_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='marks',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='responsesubmission',
            name='marks',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='responsesubmission',
            name='submission_date',
            field=models.DateTimeField(null=True, auto_now=True, auto_now_add=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='course_id',
            field=models.PositiveIntegerField(max_length=11),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='course_id',
            field=models.PositiveIntegerField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='order_num',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='type',
            field=models.PositiveSmallIntegerField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='assignment_id',
            field=models.PositiveIntegerField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='course_id',
            field=models.PositiveIntegerField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='order_num',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='type',
            field=models.PositiveSmallIntegerField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='essayquestion',
            name='assignment_id',
            field=models.PositiveIntegerField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='essayquestion',
            name='course_id',
            field=models.PositiveIntegerField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='essayquestion',
            name='question_num',
            field=models.PositiveSmallIntegerField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='essaysubmission',
            name='course_id',
            field=models.PositiveIntegerField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='lecture',
            name='course_id',
            field=models.PositiveIntegerField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='lecture',
            name='lecture_num',
            field=models.PositiveSmallIntegerField(default=0, max_length=7),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='lecture',
            name='week_num',
            field=models.PositiveSmallIntegerField(max_length=7),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='assignment_id',
            field=models.PositiveIntegerField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='course_id',
            field=models.PositiveIntegerField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='question_num',
            field=models.PositiveSmallIntegerField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='multiplechoicesubmission',
            name='assignment_id',
            field=models.PositiveIntegerField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='multiplechoicesubmission',
            name='course_id',
            field=models.PositiveIntegerField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='multiplechoicesubmission',
            name='question_num',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='policy',
            name='course_id',
            field=models.PositiveIntegerField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='responsequestion',
            name='assignment_id',
            field=models.PositiveIntegerField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='responsequestion',
            name='course_id',
            field=models.PositiveIntegerField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='responsequestion',
            name='question_num',
            field=models.PositiveSmallIntegerField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='responsesubmission',
            name='assignment_id',
            field=models.PositiveIntegerField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='responsesubmission',
            name='course_id',
            field=models.PositiveIntegerField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='responsesubmission',
            name='question_num',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='course_id',
            field=models.PositiveIntegerField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='truefalsequestion',
            name='assignment_id',
            field=models.PositiveIntegerField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='truefalsequestion',
            name='course_id',
            field=models.PositiveIntegerField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='truefalsequestion',
            name='question_num',
            field=models.PositiveSmallIntegerField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='truefalsesubmission',
            name='assignment_id',
            field=models.PositiveIntegerField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='truefalsesubmission',
            name='course_id',
            field=models.PositiveIntegerField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='truefalsesubmission',
            name='question_num',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='week',
            name='course_id',
            field=models.PositiveIntegerField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='week',
            name='week_num',
            field=models.PositiveSmallIntegerField(max_length=7),
            preserve_default=True,
        ),
    ]
