# -*- coding: utf-8 -*-
from django.utils.translation import ugettext_lazy as _
from django.conf import settings


# The constants to be used for the university applications.
#

APPLICATION_CREATED_STATUS_ID = 1
APPLICATION_PENDING_REVIEW_STATUS_ID = 2
APPLICATION_ACCEPTED_STATUS_ID = 3
APPLICATION_REJECTED_STATUS_ID = 4
APPLICATION_ON_HOLD_STATUS_ID = 5

APPLICATION_CREATED_STATUS_TEXT = _('Created Status')
APPLICATION_PENDING_REVIEW_STATUS_TEXT = _('Pending Review Status')
APPLICATION_ACCEPTED_STATUS_TEXT = _('Accepted Status')
APPLICATION_REJECTED_STATUS_TEXT = _('Reject Status')
APPLICATION_ON_HOLD_STATUS_TEXT = _('On Hold Status')

APPLICATION_STATUS_OPTIONS = (
    (APPLICATION_CREATED_STATUS_ID, APPLICATION_CREATED_STATUS_TEXT),
    (APPLICATION_PENDING_REVIEW_STATUS_ID, APPLICATION_PENDING_REVIEW_STATUS_TEXT),
    (APPLICATION_ACCEPTED_STATUS_ID, APPLICATION_ACCEPTED_STATUS_TEXT),
    (APPLICATION_REJECTED_STATUS_ID, APPLICATION_REJECTED_STATUS_TEXT),
    (APPLICATION_ON_HOLD_STATUS_ID, APPLICATION_ON_HOLD_STATUS_TEXT),
)
