# Generic
#
SECRET_DEBUG = True
SECRET_SECRET_KEY = '+hjm%=(6hyfz+jh+n9w3_)=#4obtl=xtn37@0fm_m3k9f7)rp7'
SECRET_ALLOWED_HOSTS = []


# Database
#
SECRET_DB_USER = "django"
SECRET_DB_PASSWORD = "123password"


# Email
#
SECRET_EMAIL_HOST = ''
SECRET_EMAIL_PORT = 587
SECRET_EMAIL_HOST_USER = ''
SECRET_EMAIL_HOST_PASSWORD = ''


# Application Specific Settings
#
APPLICATION_HAS_ADVERTISMENT = False
APPLICATION_HAS_PUBLIC_ACCESS_TO_TEACHERS = True