# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 01:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Created Status'), (2, 'Pending Review Status'), (3, 'Accepted Status'), (4, 'Reject Status'), (5, 'On Hold Status')], db_index=True, default=1, help_text='The state of the application.', verbose_name='Status')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('last_modified_by', models.ForeignKey(blank=True, help_text='The user whom last made changes to this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_foundation_application_last_modified_by_related', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='The user that this application belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'db_table': 'at_applications',
            },
        ),
    ]
